version: '3.9'

services:
  #MongoDB service
  my_mongo_db:
    container_name: my_db_container
    image: mongo:latest
    restart: always
    ports:
      - "2717:27017"
    volumes:
      - my_mongo_db:/data/db
  my_chat_api:
    container_name: my_chat_container
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      - MONGO_URI= mongodb://my_mongo_db:27017
    depends_on:
      - my_mongo_db
  my_mongo_interface:
    container_name: my_mongo_gui_container
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=my_db_container

volumes:
  my_mongo_db: {}
